# Generated by Django 5.1.7 on 2025-03-17 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeepositionassignment',
            name='assigned_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='teamleaderassignment',
            name='assigned_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='teammembership',
            name='joined_date',
            field=models.DateField(),
        ),
    ]
