# Generated by Django 5.1.7 on 2025-03-17 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risker', '0002_alter_employeepositionassignment_assigned_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='manager_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_departments', to='risker.position'),
        ),
    ]
