# Generated by Django 5.1.7 on 2025-03-20 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(max_length=50, unique=True)),
                ('asset_name', models.CharField(max_length=255)),
                ('asset_type', models.CharField(choices=[('Hardware', 'Hardware'), ('Software', 'Software'), ('Data', 'Data'), ('Service', 'Service')], default='Software', max_length=50)),
                ('description', models.TextField()),
                ('criticality_level', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=20)),
                ('owner', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MitigationAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mitigation_action_id', models.CharField(max_length=50, unique=True)),
                ('action_description', models.TextField()),
                ('priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=20)),
                ('assigned_to', models.CharField(max_length=255)),
                ('target_start_date', models.DateField()),
                ('target_end_date', models.DateField()),
                ('status', models.CharField(choices=[('To Do', 'To Do'), ('In Progress', 'In Progress'), ('On Hold', 'On Hold'), ('Completed', 'Completed')], default='To Do', max_length=20)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('expected_outcome', models.TextField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=255)),
                ('date_updated', models.DateField(auto_now=True)),
                ('updated_by', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RiskCategoryLevel1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_id', models.CharField(max_length=50, unique=True)),
                ('control_name', models.CharField(max_length=255)),
                ('control_objective', models.TextField()),
                ('control_description', models.TextField()),
                ('control_type', models.CharField(choices=[('Preventive', 'Preventive'), ('Detective', 'Detective'), ('Corrective', 'Corrective')], default='Preventive', max_length=20)),
                ('implementation_status', models.CharField(choices=[('Implemented', 'Implemented'), ('Planned', 'Planned'), ('Not Implemented', 'Not Implemented')], default='Planned', max_length=20)),
                ('effectiveness_rating', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=20)),
                ('owner', models.CharField(max_length=255)),
                ('associated_assets', models.ManyToManyField(blank=True, related_name='controls', to='risk.asset')),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='associated_controls',
            field=models.ManyToManyField(blank=True, related_name='assets', to='risk.control'),
        ),
        migrations.CreateModel(
            name='ProgressTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_tracking_id', models.CharField(max_length=50, unique=True)),
                ('date_of_update', models.DateField()),
                ('progress_update', models.TextField()),
                ('percentage_completion', models.IntegerField(default=0)),
                ('actual_start_date', models.DateField(blank=True, null=True)),
                ('actual_end_date', models.DateField(blank=True, null=True)),
                ('effectiveness_assessment', models.TextField(blank=True)),
                ('updated_residual_risk', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=20)),
                ('updated_by', models.CharField(max_length=255)),
                ('mitigation_action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_updates', to='risk.mitigationaction')),
            ],
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_id', models.CharField(max_length=50, unique=True)),
                ('risk_name', models.CharField(max_length=255)),
                ('risk_description', models.TextField()),
                ('potential_impact', models.TextField()),
                ('likelihood_of_occurrence', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=20)),
                ('inherent_risk_score', models.IntegerField(blank=True, null=True)),
                ('risk_owner', models.CharField(max_length=255)),
                ('date_identified', models.DateField()),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed'), ('Mitigating', 'Mitigating'), ('Accepted', 'Accepted')], default='Open', max_length=20)),
                ('relevant_eu_regulations', models.TextField(blank=True)),
                ('associated_assets', models.ManyToManyField(blank=True, related_name='risks', to='risk.asset')),
                ('associated_controls', models.ManyToManyField(blank=True, related_name='risks', to='risk.control')),
                ('associated_mitigation_actions', models.ManyToManyField(blank=True, related_name='risks', to='risk.mitigationaction')),
            ],
        ),
        migrations.CreateModel(
            name='RCSA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rcsa_id', models.CharField(max_length=50, unique=True)),
                ('assessment_date', models.DateField()),
                ('assessed_by', models.CharField(max_length=255)),
                ('assessment_scope', models.TextField()),
                ('inherent_risk_rating', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=20)),
                ('design_effectiveness', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=20)),
                ('operating_effectiveness', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=20)),
                ('residual_risk_rating', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=20)),
                ('risk_acceptance', models.BooleanField(default=False)),
                ('findings_observations', models.TextField()),
                ('recommendations', models.TextField()),
                ('recommendation_status', models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Closed', 'Closed')], default='Open', max_length=20)),
                ('due_date_for_recommendations', models.DateField(blank=True, null=True)),
                ('responsibility_for_recommendations', models.CharField(max_length=255)),
                ('control_assessed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risk.control')),
                ('risk_assessed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risk.risk')),
            ],
        ),
        migrations.AddField(
            model_name='mitigationaction',
            name='risk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mitigation_actions', to='risk.risk'),
        ),
        migrations.AddField(
            model_name='control',
            name='associated_risks',
            field=models.ManyToManyField(blank=True, related_name='controls', to='risk.risk'),
        ),
        migrations.AddField(
            model_name='asset',
            name='associated_risks',
            field=models.ManyToManyField(blank=True, related_name='assets', to='risk.risk'),
        ),
        migrations.CreateModel(
            name='RiskCategoryLevel2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('relevant_eu_regulations', models.TextField(blank=True)),
                ('level1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level2_categories', to='risk.riskcategorylevel1')),
            ],
        ),
        migrations.AddField(
            model_name='risk',
            name='risk_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='risk.riskcategorylevel2'),
        ),
    ]
