# Generated by Django 5.1.7 on 2025-03-20 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskcategorylevel1',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='riskcategorylevel2',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
