# Generated by Django 5.1.7 on 2025-03-20 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0001_initial'),
        ('risk', '0002_riskcategorylevel1_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risk',
            name='risk_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_risks', to='org.department'),
        ),
    ]
