# Generated by Django 5.1.7 on 2025-03-20 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0001_initial'),
        ('risk', '0003_alter_risk_risk_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_assets', to='org.department'),
        ),
    ]
