# Generated by Django 5.1.7 on 2025-03-23 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0004_alter_asset_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='associated_risks',
        ),
        migrations.RemoveField(
            model_name='control',
            name='associated_risks',
        ),
    ]
