# Generated by Django 5.1.7 on 2025-03-24 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0006_remove_asset_associated_controls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risk',
            name='inherent_risk_score',
            field=models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Medium', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='risk',
            name='likelihood_of_occurrence',
            field=models.CharField(choices=[('Low', 'Low (Unlikely, annual likelihood < 10%)'), ('Medium', 'Medium (Possible, annual likelihood 10-50%)'), ('High', 'High (Almost Certain, annual likelihood > 50%)')], default='Medium', max_length=20),
        ),
    ]
