# Generated by Django 5.1.7 on 2025-03-24 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0007_alter_risk_inherent_risk_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progresstracking',
            name='updated_residual_risk',
            field=models.CharField(choices=[('Low', 'Low (Immaterial or Minor)'), ('Medium', 'Medium (Moderate)'), ('High', 'High (Significant)'), ('Critical', 'Critical (Severe)')], default='Medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='rcsa',
            name='inherent_risk_rating',
            field=models.CharField(choices=[('Low', 'Low (Immaterial or Minor)'), ('Medium', 'Medium (Moderate)'), ('High', 'High (Significant)'), ('Critical', 'Critical (Severe)')], default='Medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='rcsa',
            name='residual_risk_rating',
            field=models.CharField(choices=[('Low', 'Low (Immaterial or Minor)'), ('Medium', 'Medium (Moderate)'), ('High', 'High (Significant)'), ('Critical', 'Critical (Severe)')], default='Medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='risk',
            name='inherent_risk_score',
            field=models.CharField(blank=True, choices=[('Low', 'Low (Immaterial or Minor)'), ('Medium', 'Medium (Moderate)'), ('High', 'High (Significant)'), ('Critical', 'Critical (Severe)')], default='Medium', max_length=20, null=True),
        ),
    ]
