# Generated by Django 5.1.7 on 2025-03-24 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0008_alter_progresstracking_updated_residual_risk_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='risk',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='risks', to='risk.tag'),
        ),
    ]
