# Generated by Django 5.1.7 on 2025-03-30 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0001_initial'),
        ('risk', '0009_tag_risk_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mitigationaction',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mitigation_actions', to='org.position'),
        ),
    ]
